changelog:
  exclude:
    labels:
      - repo
  categories:
    - title: Program Changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependecy Updates
      labels:
        - dependencies
